############################################
##               CONFIGURATION            ##
############################################
homeassistant:
  packages: !include_dir_named packages
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_legacy_api_password
#    - type: homeassistant
#    - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - 10.3.1.1
#        - 10.3.1.17
#  auth_mfa_modules:
#    - type: totp
#      name: Authenticator app

config:
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret http_base_url

system_health:
discovery:

logger:
  default: warning

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

hacs:
  token: !secret my_github_access_token

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: true
  entity_config:
    script.turn_on_kitchen_light:
      expose: false
    script.turn_off_kitchen_light:
      expose: false
    input_boolean.kitchen_light:
      expose: false
    script.turn_on_speaker_light:
      expose: false
    script.turn_off_speaker_light:
      expose: false
    input_boolean.speaker_light:
      expose: false
    switch.speaker_light:
      expose: false
    switch.kitchen_light:
      expose: false