############################################
##               AFVALWIJZER              ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    sensor.trash_gft:
      entity_picture: /local/icons/mijnafvalwijzer/gft.png
      friendly_name: GFT
    sensor.trash_papier:
      entity_picture: /local/icons/mijnafvalwijzer/papier.png
      friendly_name: Papier
    sensor.trash_restafval:
      entity_picture: /local/icons/mijnafvalwijzer/rest.png
      friendly_name: Restafval
    sensor.trash_grofvuil:
      entity_picture: /local/icons/mijnafvalwijzer/grof.png
      friendly_name: Grof vuil
    sensor.trash_kca:
      entity_picture: /local/icons/mijnafvalwijzer/kca.png
      friendly_name: KCA
    sensor.trash_takken:
      entity_picture: /local/icons/mijnafvalwijzer/takken.png
      friendly_name: Takken
    sensor.trash_kleding:
      entity_picture: /local/icons/mijnafvalwijzer/kleding.png
      friendly_name: Kleding
    sensor.trash_today:
      friendly_name: Vandaag
    sensor.trash_tomorrow:
      friendly_name: Morgen
    sensor.trash_next:
      friendly_name: In dagen

###### SENSORS------------------------------
sensor:
  - platform: mijnafvalwijzer
    postcode: !secret afvalwijzer_postcode
    huisnummer: !secret afvalwijzer_huisnummer
#    toevoeging:
    label_geen: 'Geen'

  - platform: template
    sensors:
      trash_today_custom:
        friendly_name: "Vandaag"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/{{states.sensor.trash_today.state}}.png"
        value_template: "{{states.sensor.trash_today.state}}"
      trash_tomorrow_custom:
        friendly_name: "Afval morgen"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/{{states.sensor.trash_tomorrow.state}}.png"
        value_template: "{{states.sensor.trash_tomorrow.state}}"
      trash_gft_custom:
        friendly_name: "GFT"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/gft.png"
        value_template: "{{states.sensor.trash_gft.state}}"
      trash_papier_custom:
        friendly_name: "Papier"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/papier.png"
        value_template: "{{states.sensor.trash_papier.state}}"
      trash_restafval_custom:
        friendly_name: "Restafval"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/rest.png"
        value_template: "{{states.sensor.trash_restafval.state}}"
      trash_grofvuil_custom:
        friendly_name: "Grof afval"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/grofvuil.png"
        value_template: "{{states.sensor.trash_grofvuil.state}}"
      trash_kca_custom:
        friendly_name: "Chemisch"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/kca.png"
        value_template: "{{states.sensor.trash_kca.state}}"
      trash_takken_custom:
        friendly_name: "Takken"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/takken.png"
        value_template: "{{states.sensor.trash_takken.state}}"
      trash_kleding_custom:
        friendly_name: "Kleding"
        icon_template: >-
          mdi:delete-empty
        entity_picture_template: "/local/icons/mijnafvalwijzer/kleding.png"
        value_template: "{{states.sensor.trash_kleding.state}}"

automation:
- alias: 'Notify of which container will be pickedup today'
  initial_state: 'on'
  hide_entity: false
  trigger:
  - platform: time
    at: '07:00:00'
  condition:
  - condition: template
    value_template: "{{ states('sensor.trash_today') != 'Geen' }}"
  - condition: template
    value_template: "{{ states.sensor.trash_today.state | trim != '' }}"
  action:
  - service: persistent_notification.create
    data_template:
      message: 'Vandaag kan de {{ states.sensor.trash_today.state }} container aan de straat.'
      title: Afval
- alias: 'Notify of which container will be pickedup tomorrow'
  initial_state: 'on'
  hide_entity: false
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: template
    value_template: "{{ states('sensor.trash_tomorrow') != 'Geen' }}"
  - condition: template
    value_template: "{{ states.sensor.trash_tomorrow.state | trim != '' }}"
  action:
  - service: persistent_notification.create
    data_template:
      message: 'Morgen kan de {{ states.sensor.trash_tomorrow.state }} container aan de straat.'
      title: Afval
