############################################
##          AUTOMATIONS GLOBAL            ##
############################################
#https://www.home-assistant.io/docs/automation/trigger/
#https://www.home-assistant.io/docs/automation/condition/
#https://www.home-assistant.io/docs/automation/action/

automation:

###### Turn on lights after sunset and a running activity -------------
  - alias: 'Turn on lights after sunset and running a activity'
    initial_state: 'on'
    trigger:
    - entity_id: media_player.vsx922
      platform: state
      to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'sunset'
    action:
      service: homeassistant.turn_on
      entity_id: light.group_tv_lights

###### Set hyperion effect when hyperion goes on -------------------------
  - alias: Set hyperion effect when hyperion goes on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.hyperion
        to: 'on'
    action:
      - delay: 00:00:01
      - service: light.turn_on
        data:
          entity_id: light.hyperion
          effect: "Full color mood blobs"

###### Turn on lights after sunset and someone is home ------------------
  - alias: 'Turn on lights after sunset and someone is home'
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:00:00'
      - platform: state
        entity_id: input_boolean.tvd
        to: 'on'
      - platform: state
        entity_id: input_boolean.jmp
        to: 'on'
      - platform: state
        entity_id: input_boolean.guest
        to: 'on'
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.tvd
          state: 'on'
        - condition: state
          entity_id: input_boolean.jmp
          state: 'on'
        - condition: state
          entity_id: input_boolean.guest
          state: 'on'
    action:
      service: light.turn_on
      entity_id: light.group_tv_lights
