############################################
##             Camera Kitchen             ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      camera_kitchen:
        friendly_name: Camera Kitchen
        value_template: "{% if is_state('device_tracker.camera_kitchen', 'home') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('device_tracker.camera_kitchen', 'home') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"

###### CAMERAS -----------------------------
camera:
  - platform: ffmpeg
    input: -rtsp_transport tcp -i "rtsp://10.3.1.11:554/rtsp_live0"
    name: Camera Kitchen
