############################################
##               Camera TV                ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      camera_tv:
        friendly_name: Camera TV
        value_template: "{% if is_state('camera.camera_tv', 'idle') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('camera.camera_tv', 'idle') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"

###### CAMERAS -----------------------------
camera:
  - platform: mjpeg
    mjpeg_url: http://10.3.1.2:8081
    name: Camera TV
