############################################
##               CHROMECAST               ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    sensor.chromecast_attic:
      templates:
        icon_color: >-
          if (state === 'Connected') return 'rgb(0, 171, 0)';
          return 'rgb(255, 0, 0)';

###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      chromecast_attic:
        friendly_name: Chromecast Attic
        value_template: "{% if is_state('device_tracker.chromecast_attic', 'home') %}Connected{% else %}Offline{% endif %}"
        icon_template: "{% if is_state('device_tracker.chromecast_attic', 'home') %} mdi:cast{% else %}mdi:lan-disconnect{% endif %}"

###### AUTOMATIONS -------------------------
automation:
  - alias: Power on receiver when starting chromecast
    initial_state: 'on'
    trigger:
    - entity_id: media_player.chromecast_attic
      platform: state
      to: 'playing'
    action:
      service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "30887292"
