 ###########################################
##                DATABASE                ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: command_line
    name: db_file_size
    command: "du -m /config/home-assistant_v2.db | cut -f1"
    unit_of_measurement: 'MB'
    value_template: '{{ value | int - 1 }}'

###### RECORDER ----------------------------
recorder:
  purge_keep_days: 14
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - ensor.current_version
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_0d
      - sensor.dark_sky_daytime_high_apparent_temperature_1d
      - sensor.dark_sky_daytime_high_apparent_temperature_2d
      - sensor.dark_sky_daytime_high_apparent_temperature_3d
      - sensor.dark_sky_daytime_high_apparent_temperature_4d
      - sensor.dark_sky_daytime_high_apparent_temperature_5d
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
      - sensor.dark_sky_daytime_high_temperature_4d
      - sensor.dark_sky_daytime_high_temperature_5d
      - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
      - sensor.dark_sky_humidity_4d
      - sensor.dark_sky_humidity_5d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_icon_2d
      - sensor.dark_sky_icon_3d
      - sensor.dark_sky_icon_4d
      - sensor.dark_sky_icon_5d
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_overnight_low_apparent_temperature_0d
      - sensor.dark_sky_overnight_low_apparent_temperature_1d
      - sensor.dark_sky_overnight_low_apparent_temperature_2d
      - sensor.dark_sky_overnight_low_apparent_temperature_3d
      - sensor.dark_sky_overnight_low_apparent_temperature_4d
      - sensor.dark_sky_overnight_low_apparent_temperature_5d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      - sensor.dark_sky_overnight_low_temperature_4d
      - sensor.dark_sky_overnight_low_temperature_5d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_2d
      - sensor.dark_sky_precip_3d
      - sensor.dark_sky_precip_4d
      - sensor.dark_sky_precip_5d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_accumulation_2d
      - sensor.dark_sky_precip_accumulation_3d
      - sensor.dark_sky_precip_accumulation_4d
      - sensor.dark_sky_precip_accumulation_5d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_intensity_2d
      - sensor.dark_sky_precip_intensity_3d
      - sensor.dark_sky_precip_intensity_4d
      - sensor.dark_sky_precip_intensity_5d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_precip_probability_2d
      - sensor.dark_sky_precip_probability_3d
      - sensor.dark_sky_precip_probability_4d
      - sensor.dark_sky_precip_probability_5d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
      - sensor.dark_sky_pressure_4d
      - sensor.dark_sky_pressure_5d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
      - sensor.dark_sky_summary_4d
      - sensor.dark_sky_summary_5d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_uv_index_2d
      - sensor.dark_sky_uv_index_3d
      - sensor.dark_sky_uv_index_4d
      - sensor.dark_sky_uv_index_5d
      - sensor.dark_sky_visibility
      - sensor.dark_sky_visibility_0d
      - sensor.dark_sky_visibility_1d
      - sensor.dark_sky_visibility_2d
      - sensor.dark_sky_visibility_3d
      - sensor.dark_sky_visibility_4d
      - sensor.dark_sky_visibility_5d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_bearing_2d
      - sensor.dark_sky_wind_bearing_3d
      - sensor.dark_sky_wind_bearing_4d
      - sensor.dark_sky_wind_bearing_5d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d
      - sensor.dark_sky_wind_speed_2d
      - sensor.dark_sky_wind_speed_3d
      - sensor.dark_sky_wind_speed_4d
      - sensor.dark_sky_wind_speed_5d
      - sensor.tram_23
      - sensor.tram_23_templated
      - sensor.tram_23_future_1
      - sensor.tram_23_future_1_templated
      - sensor.tram_23_future_2
      - sensor.tram_23_future_2_templated
      - sensor.tram_23_future_3
      - sensor.tram_23_future_3_templated
      - sensor.tram_23_future_4
      - sensor.tram_23_future_4_templated
      - sensor.bus_140
      - sensor.bus_140_templated
      - sensor.bus_140_future_1
      - sensor.bus_140_future_1_templated
      - sensor.bus_140_future_2
      - sensor.bus_140_future_2_templated
      - sensor.bus_140_future_3
      - sensor.bus_140_future_3_templated
      - sensor.bus_140_future_4
      - sensor.bus_140_future_4_templated
      - sensor.bus_183
      - sensor.bus_183_templated
      - sensor.bus_183_future_1
      - sensor.bus_183_future_1_templated
      - sensor.bus_183_future_2
      - sensor.bus_183_future_2_templated
      - sensor.bus_183_future_3
      - sensor.bus_183_future_3_templated
      - sensor.bus_183_future_4
      - sensor.bus_183_future_4_templated