############################################
##                DEFCAM02                ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      defcam02:
        friendly_name: DEF-CAM-02
        value_template: "{% if is_state('camera.defcam02', 'idle') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('camera.defcam02', 'idle') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"

###### CAMERAS -----------------------------
camera:
  - platform: mjpeg
    mjpeg_url: http://10.3.1.2:8081
    name: defcam02
