############################################
##                DEFCAM01                ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      defcam01:
        friendly_name: DEF-CAM-01
        value_template: "{% if is_state('device_tracker.defcam01', 'home') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('device_tracker.defcam01', 'home') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"

###### CAMERAS -----------------------------
camera:
  - platform: ffmpeg
    input:  -an -i "rtsp://10.3.1.11:554/rtsp_live0"
    name: defcam01
    authentication: true
