############################################
##              Google Home               ##
############################################
###### DEVICE TRACKER ----------------------
googlehome:
  devices:
    - host: 10.3.1.9

###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      googlehome:
        friendly_name: Google Home
        value_template: "{% if is_state('device_tracker.googlehome', 'home') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('device_tracker.googlehome', 'home') %} mdi:google-home{% else %}mdi:lan-disconnect{% endif %}"
