############################################
##               MY DEVICES               ##
############################################
group:
  my_phone:
    view: true
    icon: mdi:home
    entities:
      - device_tracker.thomas_thomasgalaxys8
      - device_tracker.ce0317134022612504
      - device_tracker.my_galaxys8_phone_ping
      - device_tracker.my_galaxys10plus_phone_ping

  wife_phone:
    view: true
    icon: mdi:home
    entities:
      - device_tracker.joella_joellagalaxys8
      - device_tracker.ce12171cac18a42f05
      - device_tracker.wife_phone_ping

###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      mygpsloggersensor:
        friendly_name: mygpsloggersensor
        value_template: "{% if is_state('device_tracker.ce0317134022612504', 'shadownet') %}home{% else %}!not_home{% endif %}"
        entity_picture_template: "{% if is_state('device_tracker.ce0317134022612504', 'shadownet') %} /local/icons/avatars/TVD.png{% else %} /local/icons/avatars/TVD.png{% endif %}"
#        icon_template: "{% if is_state('camera.camera_tv', 'idle') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"

      wifegpsloggerseensor:
        friendly_name: wifegpsloggerseensor
        value_template: "{% if is_state('device_tracker.ce12171cac18a42f05', 'shadownet') %}home{% else %}!not_home{% endif %}"
        entity_picture_template: "{% if is_state('device_tracker.ce12171cac18a42f05', 'shadownet') %} /local/icons/avatars/JMP.png{% else %} /local/icons/avatars/JMP.png{% endif %}"
#        icon_template: "{% if is_state('camera.camera_tv', 'idle') %} mdi:cctv{% else %}mdi:lan-disconnect{% endif %}"
