############################################
##           Packages / HTPC-01           ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.lasttvshows:
      icon: mdi:filmstrip
    script.update_library:
      icon: mdi:kodi
    script.lastmovies:
      icon: mdi:television-box
      friendly_name: Last Movies
#    script.movies_tvshows_living_room:
#      icon: mdi:kodi
#      friendly_name: Movies & TV Shows
    sensor.ha_version:
      friendly_name: Home Assistant Version

###### PANELS ------------------------------
panel_iframe:
  htpc:
    title: 'HTPC-01 Kodi'
    icon: mdi:kodi
    url: 'http://10.3.1.2:8180'

###### MEDIA PLAYERS -----------------------
media_player:
  - platform: kodi
    host: 10.3.1.2
    port: 8180
    username: !secret kodi_username
    password: !secret kodi_password
    name: HTPC-01 Kodi

###### SCRIPTS -----------------------------
script:
  kodi:
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "33745339"
      - alias: start kodi
        service: shell_command.kodi

###### SHELL COMMANDS ----------------------
shell_command:
  start_kodi: '/usr/bin/kodi'

###### SENSORS -----------------------------
###### SYSTEM MONITOR
sensor:
  - platform: systemmonitor
    resources:
    - type: ipv4_address
      arg: enp3s0
    - type: network_in
      arg: enp3s0
    - type: network_out
      arg: enp3s0
    - type: packets_in
      arg: enp3s0
    - type: packets_out
      arg: enp3s0
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: disk_use_percent
      arg: /home

###### INSTALLED VERSION
  - platform: command_line
    name: Installed Version
    command: /srv/homeassistant/bin/hass --version

###### UPTIME
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

###### VERSION
  - platform: version

###### HA VERSION
  - platform: template
    sensors:
      ha_version:
        value_template: "{%- if states.sensor.current_version.state == states.sensor.installed_version.state-%}{{states.sensor.installed_version.state}} {% else %}{{states.sensor.current_version.state}} Available{% endif%}"
        icon_template: >-
          {% if states.sensor.current_version.state == states.sensor.installed_version.state %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}

##### HTPC01
  - platform: template
    sensors:
      htpc01:
        friendly_name: Kodi HTPC-01
        value_template: "{% if is_state('device_tracker.htpc01', 'home') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('device_tracker.htpc01', 'home') %} mdi:kodi{% else %}mdi:lan-disconnect{% endif %}"

weblink:
  entities:
    - name: ssllabs
      url: https://www.ssllabs.com/ssltest/analyze.html?d=homeassistant.iiidefconiii.nl
