############################################
##                 IFTTT                  ##
############################################
###### IFTTT COMPONENT ---------------------
ifttt:
  key: !secret ifttt_api_key

###### SCRIPTS -----------------------------
script:
  add_to_playlist:
    alias: Add Spotify Track to Playlist
    sequence:
      - service: ifttt.trigger
        data_template:
          event: "add_to_playlist"
          value1: "{{ states.media_player.mandark.attributes.media_title }}"
          value2: "{{ states.media_player.mandark.attributes.media_artist }}"

  ifttt_notify:
    sequence:
      - service: ifttt.trigger
        data_template: {"event":"TestHA_Trigger", "value1":"{{ value1 }}", "value2":"{{ value2 }}", "value3":"{{ value3 }}"}

###### AUTOMATIONS -------------------------
automation:
  - alias: IFTTT
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
      service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'
