############################################
##               Light Speaker            ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.speakerlighton:
      icon: mdi:lightbulb-on-outline
    script.speakerlightoff:
      icon: mdi:lightbulb
    script.speakerlightfade:
      icon: mdi:all-inclusive
    script.speakerlightbright:
      icon: mdi:brightness-5
    script.speakerlightdim:
      icon: mdi:brightness-6
    script.speakerlightblue:
      icon: mdi:palette
    script.speakerlightgreen:
      icon: mdi:palette
    script.speakerlightlightblue:
      icon: mdi:palette
    script.speakerlightpink:
      icon: mdi:palette
    script.speakerlightpurple:
      icon: mdi:palette
    script.speakerlightred:
      icon: mdi:palette
    script.speakerlightyellow:
      icon: mdi:palette

###### SCRIPTS -----------------------------
script:
  turn_on_speaker_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light1"
            - "Light1"
          delay_secs: 2

  turn_off_speaker_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light2"
            - "Light2"
          delay_secs: 2

  speakerlightdim:
    alias: Speaker Light Dim
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "dim"

  speakerlightbright:
    alias: Speaker Light Bright
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "bright"

  speakerlightfade:
    alias: Speaker Light Fade
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "fade"

  speakerlightblue:
    alias: Speaker Light Blue
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "blue"

  speakerlightgreen:
    alias: Speaker Light Green
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "green"

  speakerlightlightblue:
    alias: Speaker Light  Blue
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "lightblue"

  speakerlightpink:
    alias: Speaker Light Pink
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "pink"

  speakerlightpurple:
    alias: Speaker Light Purple
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "purple"

  speakerlightred:
    alias: Speaker Light Red
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "red"

  speakerlightyellow:
    alias: Speaker Light Yellow
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "yellow"

###### INPUT BOOLEANS ----------------------
input_boolean:
  speaker_light:
    name: Speaker Light
    icon: mdi:lightbulb

###### SWITCHES ----------------------------
switch:
   - platform: template
     switches:
       speaker_light:
         friendly_name: Speaker Light
         value_template: "{{ is_state('input_boolean.speaker_light', 'on') }}"
         turn_on:
          - service: script.turn_on
            entity_id: script.turn_on_speaker_light
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.speaker_light
         turn_off:
          - service: script.turn_on
            entity_id: script.turn_off_speaker_light
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.speaker_light

###### LIGHTS ------------------------------
light:
  - platform: switch
    name: Speaker Light
    entity_id: switch.speaker_light
