############################################
##               Light Speaker            ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.speaker_light_on:
      icon: mdi:lightbulb-on-outline
    script.speaker_light_off:
      icon: mdi:lightbulb
    script.speaker_light_:
      icon: mdi:all-inclusive
    script.speaker_light_bright:
      icon: mdi:brightness-5
    script.speaker_light_dim:
      icon: mdi:brightness-6
    script.speaker_light_blue:
      icon: mdi:palette
      templates:
        icon_color: >
          if (state === 'on') return 'rgb(251, 210, 41)'; return 'rgb(54, 95, 140)';
    script.speaker_light_green:
      icon: mdi:palette
    script.speaker_light_lightblue:
      icon: mdi:palette
    script.speaker_light_pink:
      icon: mdi:palette
    script.speaker_light_purple:
      icon: mdi:palette
    script.speaker_light_red:
      icon: mdi:palette
    script.speaker_light_yellow:
      icon: mdi:palette

###### SCRIPTS -----------------------------
script:
  turn_on_speaker_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light1"
            - "Light1"
          delay_secs: 2

  turn_off_speaker_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light2"
            - "Light2"
          delay_secs: 2

  speaker_light_dim:
    alias: Speaker Light Dim
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "dim"

  speaker_light_bright:
    alias: Speaker Light Bright
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "bright"

  speaker_light_fade:
    alias: Speaker Light Fade
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "fade"

  speaker_light_blue:
    alias: Speaker Light Blue
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "blue"

  speaker_light_green:
    alias: Speaker Light Green
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "green"

  speaker_light_lightblue:
    alias: Speaker Light  Blue
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "lightblue"

  speaker_light_pink:
    alias: Speaker Light Pink
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "pink"

  speaker_light_purple:
    alias: Speaker Light Purple
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "purple"

  speaker_light_red:
    alias: Speaker Light Red
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "red"

  speaker_light_yellow:
    alias: Speaker Light Yellow
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458306"
          command: "yellow"

###### INPUT BOOLEANS ----------------------
input_boolean:
  speaker_light:
    name: Speaker Light
    icon: mdi:lightbulb

###### SWITCHES ----------------------------
switch:
   - platform: template
     switches:
       speaker_light:
         friendly_name: Speaker Light
         value_template: "{{ is_state('input_boolean.speaker_light', 'on') }}"
         turn_on:
          - service: script.turn_on
            entity_id: script.turn_on_speaker_light
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.speaker_light
         turn_off:
          - service: script.turn_on
            entity_id: script.turn_off_speaker_light
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.speaker_light

###### LIGHTS ------------------------------
light:
  - platform: switch
    name: Speaker Light
    entity_id: switch.speaker_light
