############################################
##               Light Kitchen            ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.woonkamer_movies_tvshows:
      icon: mdi:lightbulb      

###### SCRIPTS -----------------------------
script:
  turn_on_kitchen_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light3"
            - "Light3"
          delay_secs: 2

  turn_off_kitchen_light:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458302"
          command:
            - "Light4"
            - "Light4"
          delay_secs: 2

###### INPUT BOOLEANS ----------------------
input_boolean:
  kitchen_light:
    name: Kitchen light
    icon: mdi:lightbulb

###### SWITCHES ----------------------------
switch:
   - platform: template
     switches:
       kitchen_light:
         friendly_name: Kitchen Light
         value_template: "{{ is_state('input_boolean.kitchen_light', 'on') }}"
         turn_on:
          - service: script.turn_on
            entity_id: script.turn_on_kitchen_light
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.kitchen_light
         turn_off:
          - service: script.turn_on
            entity_id: script.turn_off_kitchen_light
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.kitchen_light

###### LIGHTS ------------------------------
light:
  - platform: switch
    name: Kitchen Light
    entity_id: switch.kitchen_light
