############################################
##               Laptop Wife              ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      ltjp:
        friendly_name: Laptop JP
        value_template: "{% if is_state('device_tracker.ltjoella', 'home') %}Connected{% else %}Offline{% endif %}"
        icon_template: "{% if is_state('device_tracker.ltjoella', 'home') %} mdi:laptop-windows{% else %}mdi:lan-disconnect{% endif %}"
