############################################
##                 SONARR                 ##
############################################
###### SENSORS -----------------------------
sensor:
- platform: sonarr_upcoming_media
  api_key: !secret api_key_sonarr
  host: 10.3.1.2
  port: 8989
  days: 2
  ssl: false

###### PANELS ------------------------------
panel_iframe:
  sonarr:
    title: 'Sonarr Shows Download'
    icon: mdi:filmstrip
    url: 'http://10.3.1.2:8989/sonarr/'
