############################################
##                  REBOOT                ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.reboot_mgmt01:
      icon: mdi:restart
      friendly_name: Reboot mgmt01

###### SCRIPTS -----------------------------
script:
  reboot_mgmt01:
    alias: Reboot mgmt01
    sequence:
      - alias: Reboot mgmt01
        service: shell_command.reboot_mgmt01

###### SHELL COMMANDS ----------------------
shell_command:
  reboot_mgmt01: '/usr/bin/sudo /sbin/shutdown -r now'
