############################################
##               Shutdown                 ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.shutdown:
      icon: mdi:power
      friendly_name: Shutdown

###### SCRIPTS -----------------------------
script:
  shutdown:
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "-1"
      - service: media_player.turn_off
        entity_id: media_player.chromecast_living_room
