############################################
##                 SONARR                 ##
############################################
###### SENSORS -----------------------------
sensor:
- platform: sonarr_upcoming_media
  api_key: !secret api_key_sonarr
  host: 10.3.1.2
  port: 8989
  days: 720
  ssl: false
