############################################
##                 SPEEDTEST              ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: speedtest
    monitored_conditions:
    - ping
    - download
    - upload
