############################################
##                Spotify                 ##
############################################
###### SCRIPTS -----------------------------
script:
  spotify:
    sequence:
      - service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: "42458300"
          command:
            - "PowerOn"
            - "InputDvd"

###### AUTOMATIONS -------------------------
automation:
  - alias: Power on receiver when starting spotify
    initial_state: 'on'
    trigger:
    - entity_id: media_player.chromecast_living_room
      platform: state
      to: 'playing'
    action:
      service: remote.send_command
      entity_id: remote.harmony_hub
      data:
        device: "42458300"
        command:
          - "PowerOn"
          - "InputDvd"
