############################################
##                 TABLET                 ##
############################################
###### SENSORS -----------------------------
sensor:
  - platform: template
    sensors:
      homeassistant:
        friendly_name: Home Assistant Tablet
        value_template: "{% if is_state('device_tracker.homeassistanttablet', 'home') %}Connected{% else %}!no-reply, please check!{% endif %}"
        icon_template: "{% if is_state('device_tracker.homeassistanttablet', 'home') %} mdi:tablet-android{% else %}mdi:lan-disconnect{% endif %}"

###### CAMERAS -----------------------------
camera:
  - platform: mjpeg
    mjpeg_url: http://10.3.1.17:6080/video
