############################################
##                TO DO IST               ##
############################################
###### CALENDARS ---------------------------
calendar:
  - platform: todoist
    token: !secret todoist_api
#    custom_projects:
#      - name: 'All Projects'
#      - name: 'Due Today'
#        due_date_days: 0
#      - name: 'Due This Week'
#        due_date_days: 7
#      - name: 'Math Homework'
#        labels:
#          - Homework
#        include_projects:
#          - Mathematical Structures II
#          - Calculus II

sensor:
- platform: template
  sensors:
    task0:
      value_template: "{{ state_attr('calendar.tasks', 'all_tasks')[0]}}"

- platform: template
  sensors:
    task1:
      value_template: "{{ state_attr('calendar.tasks', 'all_tasks')[1]}}"

- platform: template
  sensors:
    task2:
      value_template: "{{ state_attr('calendar.tasks', 'all_tasks')[2]}}"

- platform: template
  sensors:
    task3:
      value_template: "{{ state_attr('calendar.tasks', 'all_tasks')[3]}}"

- platform: template
  sensors:
    task4:
      value_template: "{{ state_attr('calendar.tasks', 'all_tasks')[4]}}"

- platform: template
  sensors:
    shop0:
      value_template: "{{ state_attr('calendar.shopping_list', 'all_tasks')[0]}}"

- platform: template
  sensors:
    shop1:
      value_template: "{{ state_attr('calendar.shopping_list', 'all_tasks')[1]}}"

- platform: template
  sensors:
    shop2:
      value_template: "{{ state_attr('calendar.shopping_list', 'all_tasks')[2]}}"

- platform: template
  sensors:
    shop3:
      value_template: "{{ state_attr('calendar.shopping_list', 'all_tasks')[3]}}"

- platform: template
  sensors:
    shop4:
      value_template: "{{ state_attr('calendar.shopping_list', 'all_tasks')[4]}}"
