############################################
##                Youtube                 ##
############################################
###### CUSTOMIZATIONS-----------------------
homeassistant:
  customize:
    script.youtube_living_rroom:
      icon: mdi:youtube
      friendly_name: Youtube

###### SCRIPTS -----------------------------
script:
  youtube_living_room:
    sequence:
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "30887004"

